# Generated by Django 4.2.6 on 2025-05-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feuerwehr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feuerwehr',
                'verbose_name_plural': 'Feuerwehren',
            },
        ),
        migrations.CreateModel(
            name='Kostentraeger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=255)),
                ('strasse', models.CharField(max_length=255)),
                ('plz', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kostenträger',
                'verbose_name_plural': 'Kostenträger',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=255)),
                ('vorname', models.CharField(max_length=255)),
                ('geburtsdatum', models.DateField()),
                ('geschlecht', models.CharField(choices=[('M', 'Männlich'), ('W', 'Weiblich'), ('D', 'Divers')], max_length=1)),
                ('strasse', models.CharField(max_length=255)),
                ('plz', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feuerwehr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patienten', to='feuerwehr.feuerwehr')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patienten',
            },
        ),
        migrations.CreateModel(
            name='Kontaktperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=255)),
                ('vorname', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('telefon', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kostentraeger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontaktpersonen', to='feuerwehr.kostentraeger')),
            ],
            options={
                'verbose_name': 'Kontaktperson',
                'verbose_name_plural': 'Kontaktpersonen',
            },
        ),
    ]
