# Generated by Django 4.2 on 2025-05-21 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feuerwehr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Untersuchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('untersuchungsdatum', models.DateField()),
                ('naechste_untersuchung', models.DateField(blank=True, null=True)),
                ('erstuntersuchung', models.BooleanField(default=True)),
                ('nachuntersuchung', models.BooleanField(default=False)),
                ('bewertung', models.CharField(choices=[('JA', 'Ohne Bedenken'), ('NEIN', 'Mit Bedenken'), ('BEDINGT', 'Bedingt geeignet')], max_length=10)),
                ('bemerkungen', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='untersuchungen', to='feuerwehr.patient')),
            ],
            options={
                'verbose_name': 'Untersuchung',
                'verbose_name_plural': 'Untersuchungen',
                'ordering': ['-untersuchungsdatum'],
            },
        ),
    ]
