# Generated by Django 4.2 on 2025-05-22 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feuerwehr', '0002_untersuchung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='untersuchung',
            options={'verbose_name': 'Untersuchung', 'verbose_name_plural': 'Untersuchungen'},
        ),
        migrations.AddField(
            model_name='feuerwehr',
            name='kostentraeger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feuerwehren', to='feuerwehr.kostentraeger'),
        ),
        migrations.AddField(
            model_name='kostentraeger',
            name='standard_kontakt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='feuerwehr.kontaktperson'),
        ),
        migrations.AddField(
            model_name='untersuchung',
            name='geraetegruppe',
            field=models.CharField(choices=[('1', 'Gerätegruppe 1'), ('2', 'Gerätegruppe 2'), ('3', 'Gerätegruppe 3')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='untersuchung',
            name='taucher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='untersuchung',
            name='voraussetzungen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='untersuchung',
            name='bemerkungen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='untersuchung',
            name='bewertung',
            field=models.CharField(choices=[('JA', 'Geeignet'), ('NEIN', 'Nicht geeignet'), ('BEDINGT', 'Bedingt geeignet')], max_length=10),
        ),
        migrations.AlterField(
            model_name='untersuchung',
            name='erstuntersuchung',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='untersuchung',
            unique_together={('patient', 'untersuchungsdatum')},
        ),
    ]
