# Generated by Django 4.2 on 2025-05-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feuerwehr', '0003_alter_untersuchung_options_feuerwehr_kostentraeger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='untersuchung',
            name='geraetegruppe',
        ),
        migrations.RemoveField(
            model_name='untersuchung',
            name='taucher',
        ),
        migrations.RemoveField(
            model_name='untersuchung',
            name='voraussetzungen',
        ),
    ]
